// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using deneme.Data;

#nullable disable

namespace deneme.Migrations
{
    [DbContext(typeof(TestContext))]
    [Migration("20220629172528_InitialSetup")]
    partial class InitialSetup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("deneme.Models.Sti", b =>
                {
                    b.Property<string>("EvrakNo")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("Tarih")
                        .HasColumnType("int");

                    b.Property<short>("IslemTur")
                        .HasColumnType("smallint");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("numeric(25,6)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("MalKodu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("numeric(25,6)");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("numeric(25,6)");

                    b.HasKey("EvrakNo", "Tarih", "IslemTur")
                        .HasName("pkSTI");

                    b.ToTable("STI");
                });

            modelBuilder.Entity("deneme.Models.Stk", b =>
                {
                    b.Property<string>("MalKodu")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("MalAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MalKodu")
                        .HasName("pkSTK");

                    b.ToTable("STK");
                });
#pragma warning restore 612, 618
        }
    }
}
